// lib/countries.ts
export type Country = {
  code: string;
  flag: string;
  name: string;
};

export const countries: Country[] = [
  // Afrique
  { code: "+213", flag: "DZ", name: "Algeria" },
  { code: "+244", flag: "AO", name: "Angola" },
  { code: "+229", flag: "BJ", name: "Benin" },
  { code: "+267", flag: "BW", name: "Botswana" },
  { code: "+226", flag: "BF", name: "Burkina Faso" },
  { code: "+257", flag: "BI", name: "Burundi" },
  { code: "+238", flag: "CV", name: "Cape Verde" },
  { code: "+235", flag: "TD", name: "Chad" },
  { code: "+269", flag: "KM", name: "Comoros" },
  { code: "+242", flag: "CG", name: "Congo" },
  { code: "+243", flag: "CD", name: "DR Congo" },
  { code: "+225", flag: "CI", name: "Côte d'Ivoire" },
  { code: "+253", flag: "DJ", name: "Djibouti" },
  { code: "+20", flag: "EG", name: "Egypt" },
  { code: "+240", flag: "GQ", name: "Equatorial Guinea" },
  { code: "+291", flag: "ER", name: "Eritrea" },
  { code: "+251", flag: "ET", name: "Ethiopia" },
  { code: "+241", flag: "GA", name: "Gabon" },
  { code: "+220", flag: "GM", name: "Gambia" },
  { code: "+233", flag: "GH", name: "Ghana" },
  { code: "+224", flag: "GN", name: "Guinea" },
  { code: "+245", flag: "GW", name: "Guinea-Bissau" },
  { code: "+254", flag: "KE", name: "Kenya" },
  { code: "+266", flag: "LS", name: "Lesotho" },
  { code: "+231", flag: "LR", name: "Liberia" },
  { code: "+218", flag: "LY", name: "Libya" },
  { code: "+261", flag: "MG", name: "Madagascar" },
  { code: "+265", flag: "MW", name: "Malawi" },
  { code: "+223", flag: "ML", name: "Mali" },
  { code: "+222", flag: "MR", name: "Mauritania" },
  { code: "+230", flag: "MU", name: "Mauritius" },
  { code: "+212", flag: "MA", name: "Morocco" },
  { code: "+258", flag: "MZ", name: "Mozambique" },
  { code: "+264", flag: "NA", name: "Namibia" },
  { code: "+227", flag: "NE", name: "Niger" },
  { code: "+234", flag: "NG", name: "Nigeria" },
  { code: "+250", flag: "RW", name: "Rwanda" },
  { code: "+262", flag: "RE", name: "Réunion" },
  { code: "+290", flag: "SH", name: "Saint Helena" },
  { code: "+239", flag: "ST", name: "Sao Tome & Principe" },
  { code: "+221", flag: "SN", name: "Senegal" },
  { code: "+248", flag: "SC", name: "Seychelles" },
  { code: "+232", flag: "SL", name: "Sierra Leone" },
  { code: "+252", flag: "SO", name: "Somalia" },
  { code: "+27", flag: "ZA", name: "South Africa" },
  { code: "+211", flag: "SS", name: "South Sudan" },
  { code: "+249", flag: "SD", name: "Sudan" },
  { code: "+268", flag: "SZ", name: "Eswatini" },
  { code: "+255", flag: "TZ", name: "Tanzania" },
  { code: "+228", flag: "TG", name: "Togo" },
  { code: "+216", flag: "TN", name: "Tunisia" },
  { code: "+256", flag: "UG", name: "Uganda" },
  { code: "+260", flag: "ZM", name: "Zambia" },
  { code: "+263", flag: "ZW", name: "Zimbabwe" },

  // Amérique du Nord
  { code: "+1", flag: "US", name: "United States" },
  { code: "+1", flag: "CA", name: "Canada" },
  { code: "+52", flag: "MX", name: "Mexico" },

  // Amérique Centrale
  { code: "+501", flag: "BZ", name: "Belize" },
  { code: "+506", flag: "CR", name: "Costa Rica" },
  { code: "+503", flag: "SV", name: "El Salvador" },
  { code: "+502", flag: "GT", name: "Guatemala" },
  { code: "+504", flag: "HN", name: "Honduras" },
  { code: "+505", flag: "NI", name: "Nicaragua" },
  { code: "+507", flag: "PA", name: "Panama" },

  // Caraïbes
  { code: "+1-264", flag: "AI", name: "Anguilla" },
  { code: "+1-268", flag: "AG", name: "Antigua & Barbuda" },
  { code: "+1-246", flag: "BB", name: "Barbados" },
  { code: "+1-441", flag: "BM", name: "Bermuda" },
  { code: "+1-345", flag: "KY", name: "Cayman Islands" },
  { code: "+53", flag: "CU", name: "Cuba" },
  { code: "+1-767", flag: "DM", name: "Dominica" },
  { code: "+1-809", flag: "DO", name: "Dominican Republic" },
  { code: "+1-829", flag: "DO", name: "Dominican Republic" },
  { code: "+1-849", flag: "DO", name: "Dominican Republic" },
  { code: "+1-473", flag: "GD", name: "Grenada" },
  { code: "+509", flag: "HT", name: "Haiti" },
  { code: "+1-876", flag: "JM", name: "Jamaica" },
  { code: "+1-664", flag: "MS", name: "Montserrat" },
  { code: "+1-787", flag: "PR", name: "Puerto Rico" },
  { code: "+1-939", flag: "PR", name: "Puerto Rico" },
  { code: "+1-869", flag: "KN", name: "St. Kitts & Nevis" },
  { code: "+1-758", flag: "LC", name: "St. Lucia" },
  { code: "+1-784", flag: "VC", name: "St. Vincent & Grenadines" },
  { code: "+1-868", flag: "TT", name: "Trinidad & Tobago" },
  { code: "+1-649", flag: "TC", name: "Turks & Caicos" },
  { code: "+1-340", flag: "VI", name: "US Virgin Islands" },

  // Amérique du Sud
  { code: "+54", flag: "AR", name: "Argentina" },
  { code: "+591", flag: "BO", name: "Bolivia" },
  { code: "+55", flag: "BR", name: "Brazil" },
  { code: "+56", flag: "CL", name: "Chile" },
  { code: "+57", flag: "CO", name: "Colombia" },
  { code: "+593", flag: "EC", name: "Ecuador" },
  { code: "+500", flag: "FK", name: "Falkland Islands" },
  { code: "+594", flag: "GF", name: "French Guiana" },
  { code: "+598", flag: "UY", name: "Uruguay" },
  { code: "+58", flag: "VE", name: "Venezuela" },
  { code: "+595", flag: "PY", name: "Paraguay" },
  { code: "+51", flag: "PE", name: "Peru" },
  { code: "+597", flag: "SR", name: "Suriname" },
  { code: "+592", flag: "GY", name: "Guyana" },

  // Asie
  { code: "+93", flag: "AF", name: "Afghanistan" },
  { code: "+374", flag: "AM", name: "Armenia" },
  { code: "+994", flag: "AZ", name: "Azerbaijan" },
  { code: "+973", flag: "BH", name: "Bahrain" },
  { code: "+880", flag: "BD", name: "Bangladesh" },
  { code: "+975", flag: "BT", name: "Bhutan" },
  { code: "+673", flag: "BN", name: "Brunei" },
  { code: "+855", flag: "KH", name: "Cambodia" },
  { code: "+86", flag: "CN", name: "China" },
  { code: "+357", flag: "CY", name: "Cyprus" },
  { code: "+995", flag: "GE", name: "Georgia" },
  { code: "+91", flag: "IN", name: "India" },
  { code: "+62", flag: "ID", name: "Indonesia" },
  { code: "+98", flag: "IR", name: "Iran" },
  { code: "+964", flag: "IQ", name: "Iraq" },
  { code: "+972", flag: "IL", name: "Israel" },
  { code: "+81", flag: "JP", name: "Japan" },
  { code: "+962", flag: "JO", name: "Jordan" },
  { code: "+7", flag: "KZ", name: "Kazakhstan" },
  { code: "+965", flag: "KW", name: "Kuwait" },
  { code: "+996", flag: "KG", name: "Kyrgyzstan" },
  { code: "+856", flag: "LA", name: "Laos" },
  { code: "+961", flag: "LB", name: "Lebanon" },
  { code: "+60", flag: "MY", name: "Malaysia" },
  { code: "+960", flag: "MV", name: "Maldives" },
  { code: "+976", flag: "MN", name: "Mongolia" },
  { code: "+95", flag: "MM", name: "Myanmar" },
  { code: "+977", flag: "NP", name: "Nepal" },
  { code: "+850", flag: "KP", name: "North Korea" },
  { code: "+968", flag: "OM", name: "Oman" },
  { code: "+92", flag: "PK", name: "Pakistan" },
  { code: "+63", flag: "PH", name: "Philippines" },
  { code: "+974", flag: "QA", name: "Qatar" },
  { code: "+966", flag: "SA", name: "Saudi Arabia" },
  { code: "+65", flag: "SG", name: "Singapore" },
  { code: "+82", flag: "KR", name: "South Korea" },
  { code: "+94", flag: "LK", name: "Sri Lanka" },
  { code: "+963", flag: "SY", name: "Syria" },
  { code: "+886", flag: "TW", name: "Taiwan" },
  { code: "+992", flag: "TJ", name: "Tajikistan" },
  { code: "+66", flag: "TH", name: "Thailand" },
  { code: "+90", flag: "TR", name: "Turkey" },
  { code: "+993", flag: "TM", name: "Turkmenistan" },
  { code: "+971", flag: "AE", name: "United Arab Emirates" },
  { code: "+998", flag: "UZ", name: "Uzbekistan" },
  { code: "+84", flag: "VN", name: "Vietnam" },
  { code: "+967", flag: "YE", name: "Yemen" },

  // Europe
  { code: "+355", flag: "AL", name: "Albania" },
  { code: "+376", flag: "AD", name: "Andorra" },
  { code: "+43", flag: "AT", name: "Austria" },
  { code: "+375", flag: "BY", name: "Belarus" },
  { code: "+32", flag: "BE", name: "Belgium" },
  { code: "+387", flag: "BA", name: "Bosnia & Herzegovina" },
  { code: "+359", flag: "BG", name: "Bulgaria" },
  { code: "+385", flag: "HR", name: "Croatia" },
  { code: "+420", flag: "CZ", name: "Czech Republic" },
  { code: "+45", flag: "DK", name: "Denmark" },
  { code: "+372", flag: "EE", name: "Estonia" },
  { code: "+298", flag: "FO", name: "Faroe Islands" },
  { code: "+358", flag: "FI", name: "Finland" },
  { code: "+33", flag: "FR", name: "France" },
  { code: "+689", flag: "PF", name: "French Polynesia" },
  { code: "+49", flag: "DE", name: "Germany" },
  { code: "+350", flag: "GI", name: "Gibraltar" },
  { code: "+30", flag: "GR", name: "Greece" },
  { code: "+299", flag: "GL", name: "Greenland" },
  { code: "+36", flag: "HU", name: "Hungary" },
  { code: "+354", flag: "IS", name: "Iceland" },
  { code: "+353", flag: "IE", name: "Ireland" },
  { code: "+39", flag: "IT", name: "Italy" },
  { code: "+383", flag: "XK", name: "Kosovo" },
  { code: "+371", flag: "LV", name: "Latvia" },
  { code: "+423", flag: "LI", name: "Liechtenstein" },
  { code: "+370", flag: "LT", name: "Lithuania" },
  { code: "+352", flag: "LU", name: "Luxembourg" },
  { code: "+356", flag: "MT", name: "Malta" },
  { code: "+373", flag: "MD", name: "Moldova" },
  { code: "+377", flag: "MC", name: "Monaco" },
  { code: "+382", flag: "ME", name: "Montenegro" },
  { code: "+31", flag: "NL", name: "Netherlands" },
  { code: "+47", flag: "NO", name: "Norway" },
  { code: "+48", flag: "PL", name: "Poland" },
  { code: "+351", flag: "PT", name: "Portugal" },
  { code: "+40", flag: "RO", name: "Romania" },
  { code: "+7", flag: "RU", name: "Russia" },
  { code: "+378", flag: "SM", name: "San Marino" },
  { code: "+381", flag: "RS", name: "Serbia" },
  { code: "+421", flag: "SK", name: "Slovakia" },
  { code: "+386", flag: "SI", name: "Slovenia" },
  { code: "+34", flag: "ES", name: "Spain" },
  { code: "+46", flag: "SE", name: "Sweden" },
  { code: "+41", flag: "CH", name: "Switzerland" },
  { code: "+380", flag: "UA", name: "Ukraine" },
  { code: "+44", flag: "GB", name: "United Kingdom" },
  { code: "+379", flag: "VA", name: "Vatican City" },

  // Océanie
  { code: "+61", flag: "AU", name: "Australia" },
  { code: "+672", flag: "NF", name: "Norfolk Island" },
  { code: "+677", flag: "SB", name: "Solomon Islands" },
  { code: "+679", flag: "FJ", name: "Fiji" },
  { code: "+682", flag: "CK", name: "Cook Islands" },
  { code: "+683", flag: "NU", name: "Niue" },
  { code: "+685", flag: "WS", name: "Samoa" },
  { code: "+686", flag: "KI", name: "Kiribati" },
  { code: "+687", flag: "NC", name: "New Caledonia" },
  { code: "+688", flag: "TV", name: "Tuvalu" },
  { code: "+690", flag: "TK", name: "Tokelau" },
  { code: "+691", flag: "FM", name: "Micronesia" },
  { code: "+692", flag: "MH", name: "Marshall Islands" },
  { code: "+64", flag: "NZ", name: "New Zealand" },
  { code: "+675", flag: "PG", name: "Papua New Guinea" },
  { code: "+676", flag: "TO", name: "Tonga" },
  { code: "+678", flag: "VU", name: "Vanuatu" },
  { code: "+680", flag: "PW", name: "Palau" },
  { code: "+681", flag: "WF", name: "Wallis & Futuna" },
];